'use client';
import { useEffect, useMemo, useState } from 'react';
const clubs=['Bayern Monachium','Ajax Amsterdam','AS Roma','TSV 1860 Monachium','Newcastle United','FC Porto','AC Milan','FC Barcelona','AS Monaco','Manchester City','Inter Mediolan','Legion Komarów','Real Madryt','Borussia Dortmund','Fulham','West Ham United','Gwardia Warszawa','Paris Saint-Germain','Wisła Kraków','Juventus'];
const seedPlayers=[];
const awardTypes=['Złota Piłka SLPN1','Król Strzelców','Najlepszy Bramkarz','MVP Sezonu','Odkrycie Sezonu','Nagroda Fair Play'];
function initials(n){return n.split(' ').map(x=>x[0]).slice(0,3).join('').toUpperCase()}
export default function Home(){
 const [tab,setTab]=useState('start'); const [user,setUser]=useState(null); const [players,setPlayers]=useState([]); const [awards,setAwards]=useState([]); const [modal,setModal]=useState(false);
 useEffect(()=>{fetch('/api/session').then(r=>r.json()).then(x=>setUser(x.user)); setPlayers(JSON.parse(localStorage.getItem('slpn_players')||'[]')); setAwards(JSON.parse(localStorage.getItem('slpn_awards')||'[]'));},[]);
 const savePlayers=v=>{setPlayers(v);localStorage.setItem('slpn_players',JSON.stringify(v))}; const saveAwards=v=>{setAwards(v);localStorage.setItem('slpn_awards',JSON.stringify(v))};
 const stats=useMemo(()=>({players:players.length,clubs:clubs.length,awards:awards.length}),[players,awards]);
 function addPlayer(e){e.preventDefault();const f=new FormData(e.currentTarget);const p={id:crypto.randomUUID(),name:f.get('name'),club:f.get('club'),position:f.get('position'),goals:0,assists:0};savePlayers([...players,p]);e.currentTarget.reset()}
 function giveAward(e){e.preventDefault();const f=new FormData(e.currentTarget),pid=f.get('player');const p=players.find(x=>x.id===pid);if(!p)return;saveAwards([{id:crypto.randomUUID(),playerId:pid,player:p.name,club:p.club,type:f.get('type'),season:f.get('season'),date:new Date().toISOString()},...awards]);e.currentTarget.reset()}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});location.reload()}
 return <main>
  <header><button className="brand" onClick={()=>setTab('start')}><img src="/logo.png"/><span><b>SLPN1</b><small>SUPER LIGA PIŁKI NOŻNEJ</small></span></button><nav>
   {[['start','Pulpit'],['players','Kadra'],['stats','Ranking'],['awards','Galeria chwały'],['clubs','Kluby']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}
  </nav><button className="login" onClick={()=>setModal(true)}>{user?'Moje konto':'Połącz konto'}</button></header>
  {tab==='start'&&<><section className="hero"><div className="eyebrow">SEZON 2026 • OFICJALNY PORTAL</div><h1>Tu zaczyna się<br/><em>Twoja historia.</em></h1><p>Nowy, czysty portal SLPN1. Zawodnicy, kluby, statystyki i nagrody w jednym miejscu.</p><div className="heroActions"><button onClick={()=>setTab('clubs')}>Poznaj kluby</button><button className="ghost" onClick={()=>setTab('players')}>Zobacz kadrę</button></div></section><section className="numbers"><div><b>{stats.clubs}</b><span>klubów</span></div><div><b>{stats.players}</b><span>zawodników</span></div><div><b>{stats.awards}</b><span>przyznanych nagród</span></div></section></>}
  {tab==='clubs'&&<section className="content"><div className="sectionHead"><span>UCZESTNICY</span><h2>Kluby ligi</h2><p>Bez oficjalnych herbów. Każdy klub ma własny, neutralny znak ligowy.</p></div><div className="clubGrid">{clubs.map((c,i)=><article className="club" key={c}><div className="crest">{initials(c)}</div><small>KLUB {String(i+1).padStart(2,'0')}</small><h3>{c}</h3><span>{players.filter(p=>p.club===c).length} zawodników</span></article>)}</div></section>}
  {tab==='players'&&<section className="content"><div className="sectionHead"><span>KADRA LIGI</span><h2>Zawodnicy</h2><p>Składy są puste. Dodawanie działa z panelu właściciela.</p></div>{user?.role==='owner'&&<form className="panelForm" onSubmit={addPlayer}><input name="name" placeholder="Nazwa zawodnika" required/><select name="club" required><option value="">Wybierz klub</option>{clubs.map(c=><option>{c}</option>)}</select><select name="position"><option>Napastnik</option><option>Pomocnik</option><option>Obrońca</option><option>Bramkarz</option></select><button>Dodaj zawodnika</button></form>}<div className="playerList">{players.length?players.map(p=><article><div className="avatar">{initials(p.name)}</div><div><h3>{p.name}</h3><p>{p.club} • {p.position}</p></div>{user?.role==='owner'&&<button className="remove" onClick={()=>savePlayers(players.filter(x=>x.id!==p.id))}>Usuń</button>}</article>):<div className="empty">Brak zawodników. Właściciel może dodać pierwszego po zalogowaniu.</div>}</div></section>}
  {tab==='stats'&&<section className="content"><div className="sectionHead"><span>LICZBY</span><h2>Ranking zawodników</h2><p>Ranking pojawi się po dodaniu zawodników i statystyk.</p></div><div className="table"><div className="tr head"><span>#</span><span>Zawodnik</span><span>Klub</span><span>Gole</span><span>Asysty</span></div>{players.map((p,i)=><div className="tr"><span>{i+1}</span><b>{p.name}</b><span>{p.club}</span><span>{p.goals}</span><span>{p.assists}</span></div>)}</div></section>}
  {tab==='awards'&&<section className="content"><div className="sectionHead"><span>GALERIA CHWAŁY</span><h2>Nagrody</h2><p>Właściciel może przyznać dowolną nagrodę wybranemu zawodnikowi.</p></div>{user?.role==='owner'&&<form className="panelForm awardsForm" onSubmit={giveAward}><select name="player" required><option value="">Wybierz zawodnika</option>{players.map(p=><option value={p.id}>{p.name} • {p.club}</option>)}</select><select name="type">{awardTypes.map(a=><option>{a}</option>)}</select><input name="season" placeholder="Sezon, np. 2026" required/><button>Przyznaj nagrodę</button></form>}<div className="awardGrid">{awards.length?awards.map(a=><article><div className="trophy">★</div><small>{a.season}</small><h3>{a.type}</h3><b>{a.player}</b><p>{a.club}</p>{user?.role==='owner'&&<button className="remove" onClick={()=>saveAwards(awards.filter(x=>x.id!==a.id))}>Cofnij nagrodę</button>}</article>):<div className="empty">Nie przyznano jeszcze żadnych nagród.</div>}</div></section>}
  {modal&&<div className="overlay" onClick={()=>setModal(false)}><div className="auth" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setModal(false)}>×</button><img src="/logo.png"/><h2>{user?'Twoje konto':'Połącz konto'}</h2><p>Połącz Discord, Roblox albo oba konta. Właściciel jest rozpoznawany po ID ustawionym w Vercel.</p>{user&&<div className="accountState"><span>Rola</span><b>{user.role==='owner'?'Właściciel':'Użytkownik'}</b></div>}<a className="oauth discord" href="/api/auth/discord">{user?.discord?'✓ Discord: '+user.discord.username:'Połącz z Discord'}</a><a className="oauth roblox" href="/api/auth/roblox">{user?.roblox?'✓ Roblox: '+user.roblox.username:'Połącz z Roblox'}</a>{user&&<button className="logout" onClick={logout}>Wyloguj wszystkie konta</button>}<small className="safe">Hasła nigdy nie trafiają do tej strony. Logowanie odbywa się bezpośrednio przez Discord i Roblox.</small></div></div>}
 </main>
}
